config :
  version         : 1.0.0
  backgroundColor : '#3b3b3b'
  headerColor     : '#292929'
  headerLineColor : '#ff9124'
  linkColor       : '#ff9124'
  color           : '#ededed'
  urlLinkedIn     : 'https://www.linkedin.com/in/pierre-hanauer/'
  urlGitHub       : 'https://github.com/biliboobrian'
  urlTwitter      : 
  langs           : [en]